version: "3"
services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ${PROJECT_PATH}:/work
      - ./logs:/var/log/nginx
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./docker/php
    ports:
      - 8000:8000
    volumes:
      - ${PROJECT_PATH}:/work
      - ./docker/ash:/etc/profile.d
      - ./logs:/var/log/php
    working_dir: /work

  composer:
    build: ./docker/composer
    volumes:
      - ${PROJECT_PATH}:/work
    working_dir: /work

  db:
    build: ./docker/db
    volumes:
      - db-data:/var/lib/mysql
      - ./logs:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306

  redis:
    image: redis:alpine

volumes:
  db-data:
    driver: local
